# seek function: allows you to move the current position of the file pointer
# within a file to a specific point

# tell function:  returns the current position of the file pointer  within the file, in bytes

f=open("day51material", "r")
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
f.close()
#  seek function

f=open("day51material", "r")
print(f.seek(0))
print(f.tell())
print(f.readline())
print(f.seek(0))
print(f.readline())
print(f.seek(0))
print(f.readline())
print(f.seek(0))
print(f.readline())
print(f.seek(0))
print(f.readline())
print(f.seek(0))
f.close()
f=open("day51material", "r")
print(f.seek(20))
print(f.tell())
print(f.readline())
print(f.seek(20))
print(f.readline())
print(f.seek(20))
print(f.readline())
print(f.seek(20))
print(f.readline())
print(f.seek(20))
print(f.readline())
print(f.seek(20))
f.close()
# we can  move the file pointer where  we want